[feat] refresh 토큰 구현, doFilter에 만료된 토큰 재발급 추가로직 구현
Mind-Goal/Mind-Goal-Backend pull request #10
Opened 2024-12-30 09:18 UTC by Duhyeonkwak-korea

[feat] refresh 토큰 구현, doFilter에 만료된 토큰 재발급 추가로직 구현

2024-12-30 12:29 UTC, hwan2-99 requested changes
고생하셨습니다!!

2024-12-30 12:29 UTC, hwan2-99 commented on src/main/java/com/mindgoal/config/jwt/JwtTokenProvider.java
> +    public JwtTokenProvider(@Value("${}") String secretkey) {
해당 @value 어노테이션의 값까지 정해서 파일에 올리고 수정해주시면 좋을것 같습니다!

2024-12-30 12:29 UTC, hwan2-99 commented on src/main/java/com/mindgoal/config/jwt/JwtAuthenticationFilter.java
> +                    response.setHeader("Authorization", "Bearer " + token);
"Authorization", "Bearer " 이 두 값에 대해서 이전 pr에서 상수로 처리하면 더 좋다고 말씀드렸던 기억이 있네요!! 변경하면 좋을것 같습니다!

2024-12-30 12:29 UTC, hwan2-99 commented on src/main/java/com/mindgoal/config/jwt/JwtTokenProvider.java
> +        return TokenDto.builder()
grantType이 무조건 "Bearer" 값 밖에없는거면 빌더보단 생성자가 더 어울릴것 같아요!!

2024-12-31 01:25 UTC, TaskerJang commented
1. **JwtAuthenticationFilter.java** 개선부분:
```java
// 상수 추가
private static final String AUTHORIZATION_HEADER = "Authorization";
private static final String BEARER_PREFIX = "Bearer ";

// 토큰 처리 로직 분리
private void processValidToken(String token) {
    Authentication auth = jwtTokenProvider.getAuthentication(token);
    SecurityContextHolder.getContext().setAuthentication(auth);
}

private void processExpiredToken(String oldToken, HttpServletResponse response) {
    String username = jwtTokenProvider.getUserName(oldToken);
    TokenDto newToken = jwtTokenProvider.generateToken(username);
    response.setHeader(AUTHORIZATION_HEADER, BEARER_PREFIX + newToken.getAccessToken());
    
    Authentication auth = jwtTokenProvider.getAuthentication(newToken.getAccessToken());
    SecurityContextHolder.getContext().setAuthentication(auth);
}
```

2. **JwtTokenProvider.java** 개선부분:
```java
// 토큰 만료시간 상수 추가
private static final long ACCESS_TOKEN_VALIDITY = 1000L * 60 * 60; // 1시간
private static final long REFRESH_TOKEN_VALIDITY = 1000L * 60 * 60 * 24; // 24시간

// 생성자 개선
public JwtTokenProvider(@Value("${jwt.secret}") String secretKey) {
    byte[] keyBytes = Decoders.BASE64.decode(secretKey);
    this.key = Keys.hmacShaKeyFor(keyBytes);
}

// 토큰 생성 메서드 분리
private Claims createClaims(String userName) {
    Claims claims = Jwts.claims();
    claims.setSubject(userName);
    claims.setIssuedAt(new Date());
    return claims;
}

private String buildToken(Claims claims, Date expiresIn) {
    return Jwts.builder()
            .setClaims(claims)
            .setExpiration(expiresIn)
            .signWith(key, SignatureAlgorithm.HS256)
            .compact();
}
```

3. **TokenDto.java** 개선부분:
```java
// Builder 대신 생성자 패턴 사용
@Getter
public class TokenDto {
    private final String grantType;
    private final String accessToken;
    private final String refreshToken;
    private final Date accessTokenExpiresIn;
    
    // 생성자에 유효성 검증 추가
    public TokenDto(String grantType, String accessToken, String refreshToken, Date accessTokenExpiresIn) {
        validateTokenData(accessToken, refreshToken);
        this.grantType = grantType;
        this.accessToken = accessToken;
        this.refreshToken = refreshToken;
        this.accessTokenExpiresIn = accessTokenExpiresIn;
    }
    
    private void validateTokenData(String accessToken, String refreshToken) {
        if (StringUtils.isEmpty(accessToken)) {
            throw new IllegalArgumentException("Access Token cannot be empty");
        }
        if (StringUtils.isEmpty(refreshToken)) {
            throw new IllegalArgumentException("Refresh Token cannot be empty");
        }
    }
}
```

주요 개선 포인트:
1. 매직 넘버를 상수로 분리
2. 토큰 처리 로직을 작은 단위로 분리
3. 토큰 데이터 유효성 검증 추가
4. 불변성 보장을 위한 final 필드 사용
5. @Value 어노테이션에 실제 프로퍼티 키 추가 (jwt.secret)

이렇게 가는건 어떨까용

2025-01-02 05:25 UTC, TaskerJang approved these changes
수고하셨습니다!

2025-01-02 12:03 UTC, hwan2-99 commented on src/main/resources/application.properties
> +jwt.secret =${jwtSecretkey}
해당 부분은 gitignore 파일에 명시 되어있는 대로 application.yml 파일에서 작성해주시면 좋을것 같습니다 + 시크릿키 밸류를 정해주시면 좋을것 같습니다!

2025-01-02 12:05 UTC, hwan2-99 commented on src/main/resources/application.properties
> +jwt.secret =${jwtSecretkey}
추가로 작업의 커밋단위를 분리하면 좋을것같아요!! [Tokendto 생성자,유효성검사 구현, JwtTokenProvider 토큰 생성 로직분리, JwtAuthenticationFilter 토큰 검증 로직 분리, application.properties 환경 변수 추가]

해당부분을 커밋을
Tokendto 생성자,유효성검사 구현
JwtTokenProvider 토큰 생성 로직분리
JwtAuthenticationFilter 토큰 검증 로직 분리
application.properties 환경 변수 추가

이렇게 4번 커밋하시면 저희가 작업 태스크를 확인하는데 좋을것 같습니다!!

2025-01-02 23:49 UTC, TaskerJang commented on src/main/resources/application.properties
> +jwt.secret =${jwtSecretkey}
좋은 의견 감사합니다!!

2025-01-04 00:36 UTC, hwan2-99 approved these changes

2025-01-04 03:56 UTC, merged